"""Type stubs for boosters._boosters_rs Rust extension module.

This file provides type hints for the native Rust extension.
It is auto-generated by pyo3-stub-gen but may be manually augmented.
"""

# Module version
__version__: str

# =============================================================================
# Config Types
# =============================================================================

class TreeConfig:
    """Configuration for tree structure."""

    max_depth: int
    n_leaves: int
    min_samples_leaf: int
    min_gain_to_split: float
    growth_strategy: str

    def __init__(
        self,
        max_depth: int = -1,
        n_leaves: int = 31,
        min_samples_leaf: int = 1,
        min_gain_to_split: float = 0.0,
        growth_strategy: str = "depthwise",
    ) -> None: ...

class RegularizationConfig:
    """Configuration for L1/L2 regularization."""

    l1: float
    l2: float
    min_hessian: float

    def __init__(
        self,
        l1: float = 0.0,
        l2: float = 1.0,
        min_hessian: float = 1.0,
    ) -> None: ...

class SamplingConfig:
    """Configuration for row and column subsampling."""

    subsample: float
    colsample: float
    colsample_bylevel: float
    goss_alpha: float
    goss_beta: float

    def __init__(
        self,
        subsample: float = 1.0,
        colsample: float = 1.0,
        colsample_bylevel: float = 1.0,
        goss_alpha: float = 0.0,
        goss_beta: float = 0.0,
    ) -> None: ...

class CategoricalConfig:
    """Configuration for categorical feature handling."""

    max_categories: int
    min_category_count: int
    max_onehot: int

    def __init__(
        self,
        max_categories: int = 256,
        min_category_count: int = 10,
        max_onehot: int = 4,
    ) -> None: ...

class EFBConfig:
    """Configuration for Exclusive Feature Bundling."""

    enable: bool
    max_conflict_rate: float

    def __init__(
        self,
        enable: bool = True,
        max_conflict_rate: float = 0.0,
    ) -> None: ...

class LinearLeavesConfig:
    """Configuration for linear models in leaf nodes."""

    enable: bool
    l2: float
    l1: float
    max_iter: int
    tolerance: float
    min_samples: int

    def __init__(
        self,
        enable: bool = False,
        l2: float = 0.01,
        l1: float = 0.0,
        max_iter: int = 10,
        tolerance: float = 1e-6,
        min_samples: int = 50,
    ) -> None: ...

class GBDTConfig:
    """Main configuration for GBDT model (placeholder)."""

    def __init__(self) -> None: ...

class GBLinearConfig:
    """Main configuration for GBLinear model (placeholder)."""

    def __init__(self) -> None: ...
